version: '3'
services:
  ##POSTGRES DATABASE FOR INVENTORY
  db-invetory:
    container_name: db-inventory
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: Juanem
      POSTGRES_PASSWORD: root
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ##MYSQL DATABASE FOR ORDERS
  db-orders:
    container_name: db-orders
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: Juanem
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306

  ##POSTGRES DATABASE FOR PRODUCTS
  db-products:
    container_name: db-products
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: Juanem
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ##POSTGRES DATABASE FOR KEYCLOAK
  db-keycloak:
    container_name: db-keycloak
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-keycloak
      POSTGRES_USER: Juanem
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  ##KEYCLOAK
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
        - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db-keycloak
      DB_PORT: 5433
      DB_USER: Juanem
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

  ##ZOOKEEPER
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ##KAFKA:
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ##ZIPKING ayuda a rastrear problemas en sistemas de arquitectura distrubuida. Da visibilidad a la propagación de las solicitudes entre los servicios
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"